In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
np.arange(30)[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [7]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.nonzero([1,2,0,0,4,0]) # индексы ненулевых элементов

(array([0, 1, 4], dtype=int64),)

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.eye(5,k=-2).transpose()

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
Z = np.random.random((10,10))
print(f'Zmin = {Z.min()}, Zmax = {Z.max()}')

Zmin = 0.01968819932911936, Zmax = 0.983655534360255


In [13]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
0 * np.nan # ноль умножить на NaN все равно NaN

nan

In [15]:
np.nan == np.nan # NaN не сравнивается

False

In [16]:
np.inf > np.nan # бесконечность и NaN не сравниваются

False

In [17]:
np.nan - np.nan # любые математические действия с NaN возвращают NaN

nan

In [18]:
.3 == 3 * .1 # 

False

In [19]:
3 * .1

0.30000000000000004

In [20]:
np.diag(np.arange(1, 5), k=-1) # создать матрицу с диагональю 1,2,3,4 под центральной

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [21]:
Z = np.zeros((8,8), dtype=int) # шахматная доска // замена значений
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [22]:
np.tile(np.array([[0,1],[1,0]]), (4,4)) # шахматная доска // разможение массивов

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [23]:
np.unravel_index(100, (6,7,8)) # индекс сотого элемента в трехмерном массиве

(1, 5, 4)

In [24]:
np.dot(np.array([[0,1],[2,3]]), np.array([[4,5],[6,7]])) # умножение матриц

array([[ 6,  7],
       [26, 31]])

In [25]:
np.dot(np.ones((5,3)), np.ones((3,2))) # умножение разноразмерных матриц

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [26]:
Z = np.arange(11)
Z[(Z > 3) & (Z <= 8)] *= -1 # замена знака у части вектора // по условию
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [27]:
Z = np.arange(11)
Z[4:9] *= -1 # замена знака на отрезке
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [28]:
Z = np.zeros((5,5))
Z += np.arange(5) # сложение матриц
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [29]:
def gen(num):
    for x in range(num):
        yield x
np.fromiter(gen(10), dtype=float) # создать вектор генератором

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
np.fromiter(range(10), dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
np.array(range(10), dtype=float) # но генератор так использовать нельзя

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [32]:
np.linspace(0,1,11)[1:-1] # вектор из 9 значений от 0 до 1 с равными интервалами

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [33]:
Z = np.random.random(10)
Z.sort() # сортировка. Сразу при создании не работает: np.random.random(10).sort()
Z

array([0.0215048 , 0.16125779, 0.16414594, 0.17878363, 0.30976031,
       0.35103113, 0.63451782, 0.63588345, 0.75393782, 0.77348327])

In [34]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.allclose(A,B) # проверка на эквивалентность

False

In [35]:
Z = np.zeros(5)
Z.flags.writeable = False # сделать массив неизменяемым
try: 
    Z[0] = 1
except: True
Z

array([0., 0., 0., 0., 0.])

In [36]:
Z = np.random.random(10)
print(Z)
print(Z.max()) # максимальное значение
print(Z.argmax()) # индекс максимального значения
Z[Z.argmax()] = 0 # заменить максимальный элемент на ноль
Z

[0.20244396 0.498454   0.4080282  0.80784301 0.34156258 0.70096536
 0.10544845 0.30000774 0.26003721 0.0335998 ]
0.8078430114047919
3


array([0.20244396, 0.498454  , 0.4080282 , 0.        , 0.34156258,
       0.70096536, 0.10544845, 0.30000774, 0.26003721, 0.0335998 ])

In [37]:
grid = 5
Z = np.zeros((grid,grid))
print(Z)
Z = np.zeros((grid,grid), [('x',float),('y',float)])
print(Z)
# стуктурированный массив с координатами x, y на сетке в квадрате [0,1] x [0,1]
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,grid), np.linspace(0,1,grid)) 
print(Z)
type(Z[1,1])

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


numpy.void

In [38]:
# минимальное и максимальное значение для каждого числового типа
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [39]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin() # np.abs(Z-v) - модуль числа, argmin - индекс минимального значения
print(f"{Z} \n{v} \n{np.abs(Z-v)} \n{Z[index]}")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 
2.4887324128630484 
[ 2.48873241  1.48873241  0.48873241  0.51126759  1.51126759  2.51126759
  3.51126759  4.51126759  5.51126759  6.51126759  7.51126759  8.51126759
  9.51126759 10.51126759 11.51126759 12.51126759 13.51126759 14.51126759
 15.51126759 16.51126759 17.51126759 18.51126759 19.51126759 20.51126759
 21.51126759 22.51126759 23.51126759 24.51126759 25.51126759 26.51126759
 27.51126759 28.51126759 29.51126759 30.51126759 31.51126759 32.51126759
 33.51126759 34.51126759 35.51126759 36.51126759 37.51126759 38.51126759
 39.51126759 40.51126759 41.51126759 42.51126759 43.51126759 44.51126759
 45.51126759 46.51126759 47.51126759 48.51126759 49.51126759 50.51126759
 51.51126759 52.

In [40]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False) # преобразование типа
Z.dtype

dtype('int32')

In [41]:
X = np.random.randint(0,10,(2, 3))
X = X.astype(np.float32, copy=False)
Y = X - X.mean(axis=1, keepdims=True) # отнять среднее из каждой строки в матрице
print(X)
print(Y)
Y.sum()

[[8. 2. 3.]
 [0. 1. 5.]]
[[ 3.6666665 -2.3333335 -1.3333335]
 [-2.        -1.         3.       ]]


-4.7683716e-07

In [42]:
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any()) # определить, есть ли в массиве нулевые столбцы

[[0 0 2 0 2 0 1 0 1 2]
 [0 0 2 0 1 2 2 2 1 0]
 [1 0 0 2 0 0 2 2 2 1]]
True


In [43]:
Z = np.arange(1,6) # задача построить новый вектор с 3 нулями между значениями 
nz = 3
Z0 = np.zeros(len(Z)*(nz+1)-nz) # новый нулевой вектор с нужной длиной
Z0[::nz+1] = Z # вставляем значения из исходного
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [44]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]] # поменять строки местами
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
